server:
  port: 8088
  servlet:
    context-path: /Colorfullcloud

swagger2:
  enable: true

qiniu:
  access:
    key: R42l9Le3Bep-31lhlh3AQg2wpRUXJ3kaE1Tc5ccP
  secret:
    key: 9EckwTxcf5TMMFaVSwFvfLDvLnqStQBwD85talYz
  bucket:
    name: geniusdsy
    host:
      name: http://picture.geniusdsy.cn

wechat:
  appid: "wxa25d8f9efe36d58a"
  secret: "e98aea2f196c5a7844056adbda2fb008"
# appid secret js_code grant_type
  code: "https://api.weixin.qq.com/sns/jscode2session"
# appid secret code grant_type
  access_token: "https://api.weixin.qq.com/sns/oauth2/access_token"
# access_token openid lang
  userinfo: "https://api.weixin.qq.com/sns/userinfo"

tencent:
  map-key: "Z6RBZ-EZF6P-MJ3DC-VVG3E-L6UQ3-NFF3X"
  current-location: "https://apis.map.qq.com/ws/location/v1/ip"
  calculated-distance: "https://apis.map.qq.com/ws/distance/v1/"
  geocoder: "https://apis.map.qq.com/ws/geocoder/v1/"

#####################
# MyBatis的配置
#####################
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true

#####################
# Druid的配置
#####################
spring:
  datasource:
    druid:
      url: jdbc:mysql://106.52.236.109:3306/colorfullcloud?useUnicode=true&useSSL=false&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      validation-query-timeout: 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
          enabled: true
        wall:
          enabled: true
          db-type: mysql
      filters: stat,wall,slf4j
  redis:
    database: 0
    host: 172.17.0.2
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
  #####################
  # 邮件的配置
  #####################
  mail:
    host: smtp.qq.com
    username: campus.mis@foxmail.com
    password: ewojbsakezxzhejd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587